[package]
name = "minip2p-rs"
description = "A minimal caller-driven libp2p implementation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
name = "minip2p"

[lints]
workspace = true

[features]
nat = ["dep:minip2p-circuit", "dep:minip2p-nat", "dep:getrandom"]
pubsub = ["dep:minip2p-pubsub", "dep:thiserror"]
discovery = ["nat", "pubsub", "dep:minip2p-discovery"]

[dependencies]
minip2p-core = { path = "../core", version = "0.1.0" }
minip2p-circuit = { path = "../circuit", version = "0.1.0", optional = true }
minip2p-discovery = { path = "../discovery", version = "0.1.0", optional = true }
minip2p-identify = { path = "../identify", version = "0.1.0" }
minip2p-identity = { path = "../identity", version = "0.1.0" }
minip2p-nat = { path = "../nat", version = "0.1.0", optional = true }
minip2p-pubsub = { path = "../pubsub", version = "0.1.0", optional = true }
minip2p-quic = { path = "../../transports/quic", version = "0.1.0" }
minip2p-swarm = { path = "../swarm", version = "0.1.0" }
minip2p-transport = { path = "../transport", version = "0.1.0" }
getrandom = { version = "0.4.3", optional = true }
thiserror = { version = "2.0.18", optional = true }

[dev-dependencies]
minip2p-relay = { path = "../relay" }
minip2p-test-support = { path = "../test-support" }
