[workspace]
resolver = "3"
exclude = ["fuzz", "bindings"]
members = [
    "crates/autonat",
    "crates/circuit",
    "crates/core",
    "crates/dcutr",
    "crates/discovery",
    "crates/ffi",
    "crates/identify",
    "crates/identity",
    "crates/mdns",
    "crates/minip2p",
    "crates/multistream-select",
    "crates/nat",
    "crates/noise",
    "crates/ping",
    "crates/platform",
    "crates/pubsub",
    "crates/relay",
    "crates/secure-mux",
    "crates/swarm",
    "crates/test-support",
    "crates/tls",
    "crates/transport",
    "crates/yamux",
    "transports/quic",
    "examples/chat",
    "examples/common",
    "examples/peer",
]

[workspace.package]
version = "0.3.1"
edition = "2024"
rust-version = "1.91"
license = "MIT"
homepage = "https://github.com/deepso7/minip2p"
repository = "https://github.com/deepso7/minip2p"
keywords = ["libp2p", "peer-to-peer", "p2p", "networking", "sans-io"]

[workspace.lints.rust]
unsafe_code = "forbid"

# Temporary Android allocator-hook fix. Remove when cloudflare/boring#518 is
# released on crates.io.
[patch.crates-io]
boring = { git = "https://github.com/deepso7/boring", rev = "de6ec29406df54911ea50dec47f40d6b6e4d6ef7" }
boring-sys = { git = "https://github.com/deepso7/boring", rev = "de6ec29406df54911ea50dec47f40d6b6e4d6ef7" }
