[package]
name = "minip2p-yamux"
description = "Bounded Sans-I/O libp2p Yamux stream multiplexer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
readme = "README.md"

[lints]
workspace = true

[features]
default = ["std"]
std = [
    "minip2p-core/std",
    "minip2p-platform/std",
    "thiserror/std",
]

[dependencies]
minip2p-core = { path = "../core", version = "0.5.2", default-features = false }
minip2p-platform = { path = "../platform", version = "0.5.2", default-features = false }
thiserror = { version = "2.0.18", default-features = false }

[dev-dependencies]
criterion = "0.8.2"
gungraun = "=0.19.4"

[[bench]]
name = "data_path"
harness = false

[[bench]]
name = "data_path_ir"
harness = false
