/* auto-generated by NAPI-RS from crates/nodejs; regenerate with `pnpm native:build` */
/* eslint-disable */
import type {
  NativeConnectionInfo,
  NativeEvent,
  NativeIdentifyInfo,
  NativeKnownPeerInfo,
  NativeOpenStream,
  NativePathKind,
  NativeRelayReservationInfo,
  Reachability,
} from "./native-shape.js";

/** A native minip2p endpoint owned by Node.js. */
export declare class NodeEndpoint {
  /** Binds a native endpoint without starting its driver. */
  constructor(secretKey: Uint8Array, config: NodeEndpointConfig)
  /** Starts the detached driver with a strong event-loop doorbell. */
  start(doorbell: () => void): void
  /** Requests shutdown without waiting for the driver thread. */
  close(): void
  /** Returns the local peer ID. */
  peerId(): string
  /** Returns bound peer addresses. */
  listenAddrs(): Array<string>
  /** Returns whether the driver accepts commands. */
  isRunning(): boolean
  /** Pulls a bounded batch of native events. */
  drainEvents(limit: number): Array<NativeEvent>
  /** Returns connected peer IDs. */
  connectedPeers(): Array<string>
  /** Returns whether Identify completed for a peer. */
  isPeerReady(peerId: string): boolean
  /** Returns the latest Identify snapshot. */
  peerInfo(peerId: string): NativeIdentifyInfo | null
  /** Accepted for compatibility; has no effect, since the driver sleeps until the endpoint's next deadline. */
  setActive(active: boolean): void
  /** Subscribes to a pubsub topic. */
  subscribe(topic: string): boolean
  /** Unsubscribes from a pubsub topic. */
  unsubscribe(topic: string): boolean
  /** Publishes one pubsub payload. */
  publish(topic: string, data: Uint8Array): void
  /** Starts one ping operation. */
  ping(peerId: string): void
  /** Registers an application protocol. */
  addProtocol(protocolId: string): void
  /** Starts opening an application stream. */
  openStream(peerId: string, protocolId: string): NativeOpenStream
  /**
   * Sends bytes on an application stream, named by its connection and
   * stream ids.
   */
  sendStream(peerId: string, connId: bigint, streamId: bigint, data: Uint8Array): void
  /** Half-closes the local stream write side. */
  closeStreamWrite(peerId: string, connId: bigint, streamId: bigint): void
  /** Resets an application stream. */
  resetStream(peerId: string, connId: bigint, streamId: bigint): void
  /** Resets and relinquishes an application stream. */
  abandonStream(peerId: string, connId: bigint, streamId: bigint): void
  /**
   * Starts one Connection attempt: a peer ID string, or an array of
   * complete peer addresses naming one peer. Returns the Connect ID.
   */
  connect(target: string | Array<string>): bigint
  /** Cancels a connection attempt. */
  cancelConnect(id: bigint): void
  /** Disconnects one peer. */
  disconnect(peerId: string): void
  /** Returns the current path to a peer. */
  path(peerId: string): NativePathKind | null
  /** Returns the transport connection selected for a peer. */
  connectionInfo(peerId: string): NativeConnectionInfo | null
  /** Returns the discovery address book. */
  knownPeers(): Array<NativeKnownPeerInfo>
  /** Returns the discovery clock. */
  discoveryNowMs(): bigint | null
  /** Returns the current reachability verdict. */
  reachability(): Reachability
  /** Returns the active relay reservation. */
  activeReservation(): NativeRelayReservationInfo | null
}

/** Builds a circuit address through a direct relay address. */
export declare function circuitAddress(relayAddress: string, peerId: string): string

/** Generates a 32-byte Ed25519 secret key. */
export declare function generateSecretKey(): Uint8Array

/** Signed-discovery configuration accepted from Node.js. */
export interface NodeDiscoveryOptions {
  /** Pubsub topic carrying signed beacons. */
  topic: string
  /** Beacon interval in milliseconds. */
  beaconIntervalMs: bigint
  /** Peer expiry interval in milliseconds. */
  peerTtlMs: bigint
  /** Whether observations may trigger dials. */
  autoDial: boolean
}

/** Endpoint configuration accepted from Node.js. */
export interface NodeEndpointConfig {
  /** Identify agent version. */
  agentVersion?: string
  /** Relay peer addresses. */
  relays: Array<string>
  /** AutoNAT server peer addresses. */
  autonatServers: Array<string>
  /** Listen multiaddresses, or the QUIC dual-stack defaults when absent. */
  listen?: Array<string>
  /** Whether all outbound paths must remain relayed. */
  forceRelay: boolean
  /** Whether unsigned pubsub messages are accepted. */
  allowUnsigned: boolean
  /** Application protocol identifiers. */
  protocols: Array<string>
  /** Signed discovery configuration. */
  discovery?: NodeDiscoveryOptions
  /** mDNS configuration. */
  mdns?: NodeMdnsOptions
}

/** mDNS configuration accepted from Node.js. */
export interface NodeMdnsOptions {
  /** Whether IPv6 multicast is enabled. */
  enableIpv6: boolean
  /** Advertised record lifetime in milliseconds. */
  ttlMs: bigint
  /** Query interval in milliseconds. */
  queryIntervalMs: bigint
  /** Maximum encoded packet size. */
  maxPacketBytes: number
  /** Maximum addresses per response. */
  maxAnnouncedAddrs: number
  /** Interface refresh interval in milliseconds. */
  interfaceRefreshMs: bigint
  /** Socket polling interval in milliseconds. */
  socketPollIntervalMs: bigint
  /** Whether observations may trigger dials. */
  autoDial: boolean
}

/** Derives a peer ID from raw Ed25519 secret key material. */
export declare function peerIdFromSecretKey(secretKey: Uint8Array): string
