packages:
  - core
  - node
  - node/npm/*
  - react-native
  - react-native/example
  - test-fixtures

allowBuilds:
  esbuild: true

catalog:
  "@types/node": 26.3.0
  "@types/react": 19.2.18
  del-cli: 7.0.0
  react: 19.2.8
  react-native: 0.87.0
  typescript: 7.0.2

minimumReleaseAgeExclude:
  - "@expo/cli@56.1.22"
  - "@expo/inline-modules@0.0.15"
  - "@expo/local-build-cache-provider@56.0.11"
  - expo@56.0.18
  - "@turbo/darwin-64@2.10.12"
  - "@turbo/darwin-arm64@2.10.12"
  - "@turbo/linux-64@2.10.12"
  - "@turbo/linux-arm64@2.10.12"
  - "@turbo/windows-64@2.10.12"
  - "@turbo/windows-arm64@2.10.12"
  - turbo@2.10.12

nodeLinker: hoisted

saveExact: true

patchedDependencies:
  uniffi-bindgen-react-native@0.31.0-5: react-native/patches/uniffi-bindgen-react-native@0.31.0-5.patch
