use std::cell::RefCell;
use std::io;
use std::pin::Pin;
use std::rc::Rc;
use std::task::{Context, Poll};

use futures::io::{AsyncRead, AsyncWrite};
use futures::task::noop_waker;
use yamux::{Config, Connection, Mode};

#[derive(Clone, Default)]
struct CaptureIo {
    bytes: Rc<RefCell<Vec<u8>>>,
}

impl AsyncRead for CaptureIo {
    fn poll_read(
        self: Pin<&mut Self>,
        _context: &mut Context<'_>,
        _buffer: &mut [u8],
    ) -> Poll<io::Result<usize>> {
        Poll::Pending
    }
}

impl AsyncWrite for CaptureIo {
    fn poll_write(
        self: Pin<&mut Self>,
        _context: &mut Context<'_>,
        buffer: &[u8],
    ) -> Poll<io::Result<usize>> {
        self.bytes.borrow_mut().extend_from_slice(buffer);
        Poll::Ready(Ok(buffer.len()))
    }

    fn poll_flush(self: Pin<&mut Self>, _context: &mut Context<'_>) -> Poll<io::Result<()>> {
        Poll::Ready(Ok(()))
    }

    fn poll_close(self: Pin<&mut Self>, _context: &mut Context<'_>) -> Poll<io::Result<()>> {
        Poll::Ready(Ok(()))
    }
}

fn main() {
    let capture = CaptureIo::default();
    let written = capture.bytes.clone();
    let mut connection = Connection::new(capture, Config::default(), Mode::Client);
    let waker = noop_waker();
    let mut context = Context::from_waker(&waker);

    let mut stream = match connection.poll_new_outbound(&mut context) {
        Poll::Ready(Ok(stream)) => stream,
        output => panic!("unexpected outbound-stream poll: {output:?}"),
    };
    match Pin::new(&mut stream).poll_write(&mut context, b"fixture-data") {
        Poll::Ready(Ok(12)) => {}
        output => panic!("unexpected stream write poll: {output:?}"),
    }
    drive(&mut connection, &mut context);

    match Pin::new(&mut stream).poll_close(&mut context) {
        Poll::Ready(Ok(())) => {}
        output => panic!("unexpected stream close poll: {output:?}"),
    }
    drive(&mut connection, &mut context);
    drop(stream);

    loop {
        match connection.poll_close(&mut context) {
            Poll::Ready(Ok(())) => break,
            Poll::Ready(Err(error)) => panic!("connection close failed: {error}"),
            Poll::Pending => continue,
        }
    }

    println!("# Generated by crates/yamux/tests/fixtures/regenerate-yamux.sh");
    println!("# Normal CI consumes this file only; it does not build the producer.");
    println!("producer=yamux-0.13.8");
    println!(
        "client_transcript={}",
        encode_hex(&without_ping_frames(&written.borrow()))
    );
}

fn drive(connection: &mut Connection<CaptureIo>, context: &mut Context<'_>) {
    match connection.poll_next_inbound(context) {
        Poll::Pending => {}
        Poll::Ready(Some(Ok(stream))) => panic!("unexpected inbound stream: {stream:?}"),
        Poll::Ready(Some(Err(error))) => panic!("connection failed: {error}"),
        Poll::Ready(None) => panic!("connection closed while driving output"),
    }
}

fn encode_hex(bytes: &[u8]) -> String {
    use std::fmt::Write;

    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(output, "{byte:02x}").unwrap();
    }
    output
}

fn without_ping_frames(bytes: &[u8]) -> Vec<u8> {
    let mut filtered = Vec::new();
    let mut offset = 0;
    while offset < bytes.len() {
        let header = bytes
            .get(offset..offset + 12)
            .expect("producer emitted a complete Yamux header");
        let frame_type = header[1];
        let payload_len = if frame_type == 0 {
            u32::from_be_bytes([header[8], header[9], header[10], header[11]]) as usize
        } else {
            0
        };
        let end = offset + 12 + payload_len;
        let frame = bytes
            .get(offset..end)
            .expect("producer emitted a complete Yamux frame");
        if frame_type != 2 {
            filtered.extend_from_slice(frame);
        }
        offset = end;
    }
    filtered
}

#[cfg(test)]
mod tests {
    use super::without_ping_frames;

    #[test]
    fn strips_only_ping_frames() {
        let ping = [0, 2, 0, 1, 0, 0, 0, 0, 1, 2, 3, 4];
        let data = [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, b'x'];
        assert_eq!(
            without_ping_frames(&[ping.as_slice(), &data].concat()),
            data
        );
    }
}
