[package]
name = "minip2p-swarm"
description = "Caller-driven protocol and connection orchestration for minip2p"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
readme = "README.md"

[lints]
workspace = true

[features]
default = ["std"]
std = [
    "minip2p-core/std",
    "minip2p-identify/std",
    "minip2p-identity/std",
    "minip2p-multistream-select/std",
    "minip2p-ping/std",
    "minip2p-transport/std",
    "thiserror/std",
    "dep:getrandom",
]

[dependencies]
minip2p-core = { path = "../core", version = "0.1.2", default-features = false }
minip2p-identify = { path = "../identify", version = "0.1.2", default-features = false }
minip2p-identity = { path = "../identity", version = "0.1.2", default-features = false, features = ["ed25519"] }
minip2p-multistream-select = { path = "../multistream-select", version = "0.1.2", default-features = false }
minip2p-ping = { path = "../ping", version = "0.1.2", default-features = false }
minip2p-transport = { path = "../transport", version = "0.1.2", default-features = false }
thiserror = { version = "2.0.18", default-features = false }
getrandom = { version = "0.4.3", optional = true }

[dev-dependencies]
minip2p-relay = { path = "../relay" }
minip2p-dcutr = { path = "../dcutr" }
minip2p-test-support = { path = "../test-support" }
