// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-minip2p.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "Minip2pSpec.h"

@interface Minip2p : NSObject <NativeMinip2pSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Minip2p : NSObject <RCTBridgeModule>
#endif

@end
