// Generated by uniffi-bindgen-react-native
#include "react-native-minip2p.h"
#include "generated/minip2p_ffi.hpp"

namespace minip2p {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeMinip2pFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}
